### ISSUE TITLE
[python-colcon-core]: colcon not in PATH?

### ISSUE THREAD

**Issue by janblumenkamp** [acxz/pkgbuilds#108]
I am trying to install ROS2 according to [these instructions](https://wiki.archlinux.org/index.php/ROS#ROS_2), but after installing `ros2-arch-deps` and therefore `python-colcon-core`, I cannot run `colcon`:

```
➜  ~ colcon
zsh: command not found: colcon
```

`rosdep` can be executed at least, so something must be wrong with the `python-colcon-core` package? Something else seems to be wrong though as it cannot find `catkin_pkg`, even though it is installed as part of `ros2-arch-deps` too:
```
➜  ~ rosdep
Traceback (most recent call last):
  File "/usr/bin/rosdep", line 33, in <module>
    sys.exit(load_entry_point('rosdep==0.20.0', 'console_scripts', 'rosdep')())
  File "/usr/bin/rosdep", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/rosdep2/__init__.py", line 45, in <module>
    from .lookup import RosdepDefinition, RosdepView, RosdepLookup, \
  File "/usr/lib/python3.9/site-packages/rosdep2/lookup.py", line 41, in <module>
    from .rospkg_loader import RosPkgLoader
  File "/usr/lib/python3.9/site-packages/rosdep2/rospkg_loader.py", line 39, in <module>
    import catkin_pkg.package
ModuleNotFoundError: No module named 'catkin_pkg'
```

Do you have an idea what might be going on?
Thanks a lot!

**Comment by acxz** [comment]
hmm don't have an idea of the top of my head

**Comment by m2-farzan** [comment]
I tested this now and it works fine. Maybe upstream devs fixed it. My bash log:

```
mostafa🐌phi ~ 
$ colcon
bash: /usr/bin/colcon: No such file or directory

mostafa🐌phi ~ 
$ yay -S python-colcon-core
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo: 13]  python-iniconfig-1.1.1-1  python-more-itertools-8.6.0-3  python-pluggy-0.13.1-4  python-apipkg-1.5-5  python-py-1.10.0-1  python-pytest-6.2.2-1  python-pytest-runner-5.2-3  python-pytest-rerunfailures-9.1.1-3  python-pytest-repeat-0.8.0-3  python-coverage-5.5-1  python-pytest-cov-2.11.1-1  python-notify2-0.3.1-5  python-empy-3.3.4-5
[Aur: 1]  python-colcon-core-0.6.1-1

  1 python-colcon-core                       (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): python-colcon-core
  1 python-colcon-core                       (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: Parsing SRCINFO (1/1): python-colcon-core
resolving dependencies...
looking for conflicting packages...

Packages (13) python-apipkg-1.5-5  python-coverage-5.5-1  python-empy-3.3.4-5
              python-iniconfig-1.1.1-1  python-more-itertools-8.6.0-3
              python-notify2-0.3.1-5  python-pluggy-0.13.1-4
              python-py-1.10.0-1  python-pytest-6.2.2-1
              python-pytest-cov-2.11.1-1  python-pytest-repeat-0.8.0-3
              python-pytest-rerunfailures-9.1.1-3  python-pytest-runner-5.2-3

Total Installed Size:  6.13 MiB

:: Proceed with installation? [Y/n] 
(13/13) checking keys in keyring                   [######################] 100%
(13/13) checking package integrity                 [######################] 100%
(13/13) loading package files                      [######################] 100%
(13/13) checking for file conflicts                [######################] 100%
(13/13) checking available disk space              [######################] 100%
:: Processing package changes...
( 1/13) installing python-iniconfig                [######################] 100%
( 2/13) installing python-more-itertools           [######################] 100%
( 3/13) installing python-pluggy                   [######################] 100%
( 4/13) installing python-apipkg                   [######################] 100%
( 5/13) installing python-py                       [######################] 100%
( 6/13) installing python-pytest                   [######################] 100%
( 7/13) installing python-pytest-runner            [######################] 100%
( 8/13) installing python-pytest-rerunfailures     [######################] 100%
( 9/13) installing python-pytest-repeat            [######################] 100%
(10/13) installing python-coverage                 [######################] 100%
Optional dependencies for python-coverage
    python-toml: for pyproject.toml support [installed]
(11/13) installing python-pytest-cov               [######################] 100%
(12/13) installing python-notify2                  [######################] 100%
(13/13) installing python-empy                     [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Making package: python-colcon-core 0.6.1-1 (Fri 02 Apr 2021 01:02:05 AM +0430)
==> Retrieving sources...
  -> Found python-colcon-core-0.6.1.tar.gz
==> Validating source files with sha256sums...
    python-colcon-core-0.6.1.tar.gz ... Passed
python-pytest not satisfied, flushing install queue
==> Making package: python-colcon-core 0.6.1-1 (Fri 02 Apr 2021 01:02:06 AM +0430)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found python-colcon-core-0.6.1.tar.gz
==> Validating source files with sha256sums...
    python-colcon-core-0.6.1.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting python-colcon-core-0.6.1.tar.gz with bsdtar
==> Sources are ready.
==> Making package: python-colcon-core 0.6.1-1 (Fri 02 Apr 2021 01:02:08 AM +0430)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
==> python-colcon-core-0.6.1-1 already made -- skipping build
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) python-colcon-core-0.6.1-1

Total Installed Size:  0.79 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) installing python-colcon-core                [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

mostafa🐌phi ~ 
$ colcon
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
              {build,test} ...

Error: No verb provided

mostafa🐌phi ~ 
$ which colcon
/usr/bin/colcon

mostafa🐌phi ~ 
$ pacman -Qo /usr/bin/colcon
/usr/bin/colcon is owned by python-colcon-core 0.6.1-1


```

**Comment by janblumenkamp** [comment]
Thanks for following up! I think it was a Python version issue on my end and some enabled pipenvs or so (ROS really seems to not handle those well). WIll close it for now.
