### ISSUE TITLE
[python-nunavut] Dependencies are out-of-date

### ISSUE THREAD

**Issue by mnme** [acxz/pkgbuilds#173]
When trying to use the nnvg cli tool, I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/nnvg", line 33, in <module>
    sys.exit(load_entry_point('nunavut==1.7.4', 'console_scripts', 'nnvg')())
  File "/usr/bin/nnvg", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/nunavut/__init__.py", line 73, in <module>
    from .lang import LanguageContext
  File "/usr/lib/python3.10/site-packages/nunavut/lang/__init__.py", line 22, in <module>
    from .._utilities import YesNoDefault, iter_package_resources
  File "/usr/lib/python3.10/site-packages/nunavut/_utilities.py", line 20, in <module>
    import importlib_resources
ModuleNotFoundError: No module named 'importlib_resources'
```

A dependency on the `importlib-resources` python package [was added][1]. I couldn't find it in the AUR.

I think the dependencies are generally not up-to-date. It looks like they [bundle][2] python-jinja and 
python-markupsafe now. The current [`setup.cfg`][3] indicates that python-pyaml is required.

[1]: https://github.com/UAVCAN/nunavut/pull/223
[2]: https://github.com/UAVCAN/nunavut/blob/89e2f20e9c3f6935b8350aa72323bc6d4a209119/README.rst#bundled-third-party-software
[3]: https://github.com/UAVCAN/nunavut/blob/89e2f20e9c3f6935b8350aa72323bc6d4a209119/setup.cfg#L38

**Comment by acxz** [comment]
> couldn't find it in the AUR.

Looks like it is in [community].

Updated deps.
I'm not handling the submodules however.

Let me know if you still get some errors.

**Comment by mnme** [comment]
Oh I completely missed the package in [community] because it's spelled with an underscore.

The CLI command works fine for my use case now. Thank you for fixing it so fast!
