### ISSUE TITLE
Build error python-pyqt5-sip4

### ISSUE THREAD

**Issue by drapado** [acxz/pkgbuilds#176]
Hi, trying to build python-pyqt5-sip4 to replace python-pyqt5 and therefore update ros-noetic-rviz. However, I get an error during build:
```bash
:: Proceed with installation? [Y/n]: y
fetching devel info...
==> Making package: python-pyqt5-sip4 5.15.6-2 (Tue 05 Apr 2022 09:58:24)
==> Retrieving sources...
  -> Downloading PyQt5-5.15.6.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0   3264      0 --:--:-- --:--:-- --:--:--  3297
100   271  100   271    0     0   1506      0 --:--:-- --:--:-- --:--:--  1506
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3163k  100 3163k    0     0  6849k      0 --:--:-- --:--:-- --:--:-- 6849k
  -> Found restore-sip4-support.patch
==> Validating source files with sha256sums...
    PyQt5-5.15.6.tar.gz ... Passed
    restore-sip4-support.patch ... Passed
==> Making package: python-pyqt5-sip4 5.15.6-2 (Tue 05 Apr 2022 09:58:25)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found PyQt5-5.15.6.tar.gz
  -> Found restore-sip4-support.patch
==> Validating source files with sha256sums...
    PyQt5-5.15.6.tar.gz ... Passed
    restore-sip4-support.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting PyQt5-5.15.6.tar.gz with bsdtar
==> Starting prepare()...
patching file sip/QtCore/QtCoremod.sip
==> Sources are ready.
python-pyqt5-sip4-5.15.6-2: parsing pkg list...
==> Making package: python-pyqt5-sip4 5.15.6-2 (Tue 05 Apr 2022 09:58:26)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.5.1', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'python-pyqt5-sip4-5.15.6-2': 
error: packages failed to build: python-pyqt5-sip4-5.15.6-2

```

**Comment by acxz** [comment]
Thx for the report! Make sure to check the previous issues first tho :smile: 

Dup of #175
