### ISSUE TITLE
[mavlink] `pymavlink.tools` module not found

### ISSUE THREAD

**Issue by acxz** [acxz/pkgbuilds#19]
```
make[1]: Entering directory '/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/build'
make[2]: Entering directory '/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/build'
make[2]: Leaving directory '/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/build'
make[2]: Entering directory '/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/build'
[  5%] Generating matrixpilot.xml-v1.0-stamp
/usr/bin/python: Error while finding module specification for 'pymavlink.tools.mavgen' (ModuleNotFoundError: No module named 'pymavlink.tools')
make[2]: *** [CMakeFiles/matrixpilot.xml-v1.0.dir/build.make:61: matrixpilot.xml-v1.0-stamp] Error 1
make[2]: Leaving directory '/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/build'
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/matrixpilot.xml-v1.0.dir/all] Error 2
make[1]: Leaving directory '/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/build'
```

**Comment by acxz** [comment]
New error:
```
Validating /home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/message_definitions/v0.9/slugs.xml
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/pymavlink/tools/mavgen.py", line 31, in <module>
    mavgen.mavgen(args, args.definitions)
  File "/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/pymavlink/generator/mavgen.py", line 136, in mavgen
    if not mavgen_validate(fname):
  File "/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/pymavlink/generator/mavgen.py", line 105, in mavgen_validate
    with open(xmlfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/acxz/vcs/git/github/acxz/pkgbuilds/mavlink/src/mavlink-1.0.12/message_definitions/v0.9/slugs.xml'
```
