### ISSUE TITLE
[python-vispy] Failed build with python 3.10, Pep517HookCaller TypeError

### ISSUE THREAD

**Issue by mahlzahn** [acxz/pkgbuilds#207]
Trying to upgrade on python 3.10 from 0.10.0-2 to 0.11.0-2 fails with following output:
```
==> Making package: python-vispy 0.11.0-2 (Tue 02 Aug 2022 11:07:16 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading python-vispy-0.11.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1654k    0 1654k    0     0  1518k      0 --:--:--  0:00:01 --:--:-- 1518k
100 2447k    0 2447k    0     0  2003k      0 --:--:--  0:00:01 --:--:-- 6049k
==> Validating source files with sha256sums...
    python-vispy-0.11.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting python-vispy-0.11.0.tar.gz with bsdtar
==> Starting build()...

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 370, in main
    built = build_call(
  File "/usr/lib/python3.10/site-packages/build/__main__.py", line 201, in build_package
    builder = _ProjectBuilder(srcdir)
  File "/usr/lib/python3.10/site-packages/build/__init__.py", line 301, in __init__
    self._hook = pep517.wrappers.Pep517HookCaller(
TypeError: Pep517HookCaller.__init__() got an unexpected keyword argument 'python_executable'

ERROR Pep517HookCaller.__init__() got an unexpected keyword argument 'python_executable'
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by acxz** [comment]
weird I can't seem to reproduce.

Have you tried clearing your AUR helper's cache?
Otherwise can you try building in a clean chroot.

**Comment by mahlzahn** [comment]
Thanks for your answer. Cleaning the AUR helper’s cache did not help. What in the end worked was removing the package and then reinstalling it.
