### ISSUE TITLE
[python-mlflow] configparser>=0.3.5 needed

### ISSUE THREAD

**Issue by PhilipMay** [acxz/pkgbuilds#21]
After installing and running this package I get the following message:

```
$ mlflow 
Traceback (most recent call last):
  File "/usr/bin/mlflow", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'configparser>=0.3.5' distribution was not found and is required by databricks-cli
``` 

Also see here: https://github.com/acxz/pkgbuilds/issues/20

**Comment by acxz** [comment]
Thx for the report! I would like to try and see what happens if I patch that `configparser` line out in the setup.py.

**Comment by PhilipMay** [comment]
> Thx for the report! I would like to try and see what happens if I patch that `configparser` line out in the setup.py.

That would be awsome.

Do you install mlflow with pip and not with pacman (your AUR package)?

**Comment by acxz** [comment]
@PhilipMay fixed. Let me know if you have any other issues. Here is the upstream PR. Labelling this as patched and keeping open until upstream provides closure to this issue.

**Comment by acxz** [comment]
Closing this issue and leaving the other open with the patched label.
