### ISSUE TITLE
[python-ray] Build error: unrecognized option --incompatible_depset_is_not_iterable=false

### ISSUE THREAD

**Issue by edlanglois** [acxz/pkgbuilds#30]
Some output with the error:
```
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=284
INFO: Reading rc options for 'build' from /home/eric/src/aur/python-ray/src/ray-ray-0.8.4/.bazelrc:
  'build' options: --enable_platform_specific_config --action_env=PATH --per_file_copt=-\.(asm|S)$,-.*/arrow/util/logging\.cc@-Werror --per_file_copt=-\.(asm|S)$,\.pb\.cc$@-w --per_file_copt=-\.(asm|S)$,external/.*@-w --per_file_copt=-\.(asm|S)$,.*/ray/raylet/reconstruction_policy_test\.cc@-Wno-inconsistent-missing-override --per_file_copt=-\.(asm|S)$,.*/_raylet\.cpp@-Wno-deprecated-declarations --per_file_copt=-\.(asm|S)$,.*/_streaming\.cpp@-Wno-deprecated-declarations --host_copt=-Wno-builtin-macro-redefined --host_copt=-Wno-inconsistent-missing-override --host_copt=-Wno-microsoft-unqualified-friend --per_file_copt=-\.(asm|S)$,external/com_github_grpc_grpc/.*@-DGRPC_BAZEL_BUILD --http_timeout_scaling=5.0 --incompatible_depset_is_not_iterable=false
ERROR: Unrecognized option: --incompatible_depset_is_not_iterable=false
Traceback (most recent call last):
  File "setup.py", line 178, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 107, in run
    subprocess.check_call(command)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '-p', '/usr/bin/python']' returned non-zero exit status 2.
```

**Comment by edlanglois** [comment]
Looks like it's been fixed upstream but missed the release https://github.com/ray-project/ray/pull/7886

**Comment by edlanglois** [comment]
And I just noticed that was you who submitted that PR so looks like you're well aware of this

**Comment by acxz** [comment]
Lol yeah, I made the fix but was too lazy to make a patch to this and I won’t be using ray until next month so I have been putting it on. Ray also has very frequent releases so I think it will be resolved very quickly. In any case thx for the report, let’s keep this issue open until it is reflected in this package.

If you want you can make the patch and update the PR and I’ll merge and push it out the AUR in a jiffy.
