### ISSUE TITLE
[python-ray] build error

### ISSUE THREAD

**Issue by pgagarinov** [acxz/pkgbuilds#40]
[1,620 / 1,842] 24 actions running
    Compiling streaming/src/queue/transport.cc; 129s linux-sandbox
    Compiling streaming/src/queue/queue.cc; 122s linux-sandbox
    Compiling src/ray/raylet/worker.cc; 122s linux-sandbox
    Compiling streaming/src/flow_control.cc; 107s linux-sandbox
    Compiling streaming/src/data_reader.cc; 107s linux-sandbox
    Compiling streaming/src/channel.cc; 107s linux-sandbox
    Compiling python/ray/streaming/_streaming.cpp; 87s linux-sandbox
    Compiling streaming/src/event_service.cc; 87s linux-sandbox ...

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/home/peter/.cache/bazel/_bazel_peter/2aa3c0257835e315527d12b7e03e37da/server/jvm.out')

Traceback (most recent call last):
  File "setup.py", line 202, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 121, in run
    subprocess.check_call(command)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '-p', '/usr/bin/python']' returned non-zero exit status 37.

**Comment by acxz** [comment]
Thx for the report @pgagarinov 
was able to reproduce it on my end.

**Comment by acxz** [comment]
@pgagarinov this should be resolved with the latest release (python-ray-0.8.6).
Feel free to reopen this if you still have issues.
