### ISSUE TITLE
[python-cfclient] build fails when using `python-cx_freeze=6.2`

### ISSUE THREAD

**Issue by goekce** [acxz/pkgbuilds#65]
Error:
```
copying /usr/lib/python3.8/site-packages/numpy/random/_common.cpython-38-x86_64-linux-gnu.so -> build/exe.linux-x86_64-3.8/lib/numpy/random/_common.cpython-38-x86_64-linux-gnu.so
===== 2020.08.25 06:08:57 =====
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/cx_Freeze/dist.py", line 342, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/cx_Freeze/dist.py", line 217, in run
    freezer.Freeze()
  File "/usr/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 645, in Freeze
    self._WriteModules(fileName, self.finder)
  File "/usr/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 536, in _WriteModules
    sourcePackageDir = os.path.dirname(module.file)
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
==> ERROR: A failure occurred in build().
    Aborting...
```

The bug is resolved by https://github.com/marcelotduarte/cx_Freeze/pull/695 . The fix will be included probably in the next release. Downgrading to [python-cx_freeze=6.1](https://archive.archlinux.org/packages/p/python-cx_freeze/python-cx_freeze-6.1-1-x86_64.pkg.tar.zst) is a workaround.

Source: [user1224797 @ SO](https://stackoverflow.com/questions/62951554/cx-freeze-gives-typeerror-expected-str-bytes-or-os-pathlike-object-not-nonety)

**Comment by goekce** [comment]
Thank you for mentioning this issue upstream @acxz , but why did you close the issue immediately?

**Comment by acxz** [comment]
Cuz the bug is resolved by upstream and cx_freeze can't do anything about it. I wanted to post the error so that if others come across it they know about the solution.

**Comment by acxz** [comment]
@goekce can you do me a favor and see if the issue still exists?
cx_freeze has been updated on arch so I believe we can close this issue but just want someone else to confirm before we close it. Thx so much.

**Comment by goekce** [comment]
tested it. LGTM!
